language: php

php:
  - "5.4"

services: mysql

install:
  - composer require drush/drush:6.*

before_script:
  - mysql -e 'CREATE DATABASE travis CHARACTER SET utf8 COLLATE utf8_general_ci;'
  - . vendor/bin/drush
