language: php

php:
  - "5.4"

services: mysql

install:
  - composer require drush/drush:6.*

before_script:
  # - mysql -e 'CREATE DATABASE travis CHARACTER SET utf8 COLLATE utf8_general_ci;'
  - php vendor/bin/drush.php site-install minimal --db-su=root --db-url=mysql://travis@127.0.0.1/travis --sites-subdir=travis --yes
